# Generated by Django 6.1 on 2026-08-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('normalized_word', models.CharField(max_length=100, unique=True)),
                ('pronunciation', models.CharField(max_length=255)),
                ('part_of_speech', models.CharField(max_length=50)),
                ('bangla_meaning', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('example_sentence', models.TextField()),
                ('difficulty', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('source', models.CharField(default='gemini', max_length=50)),
                ('generated_by', models.CharField(blank=True, max_length=100)),
                ('generation_version', models.CharField(default='v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
