# Generated by Django 6.1 on 2026-09-13 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_dailyvocabulary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVocabularyOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('daily_vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='vocabulary.dailyvocabulary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_vocabulary_opens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('daily_vocabulary', 'user'), name='unique_daily_vocabulary_open')],
            },
        ),
    ]
