# Generated by Django 6.1 on 2026-08-25 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLessonWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('daily_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_words', to='lessons.dailylesson')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_entries', to='vocabulary.vocabulary')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('daily_lesson', 'position'), name='unique_lesson_word_position'), models.UniqueConstraint(fields=('daily_lesson', 'vocabulary'), name='unique_vocabulary_per_lesson')],
            },
        ),
    ]
